language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_14f4390ac2b6_key -iv $encrypted_14f4390ac2b6_iv
  -in scremsong-web-variables.env.enc -out ./scremsong-web-variables.env -d
script:
- pwd
- ls -l
