language: python
python:
- 3.6
before_install:
  - openssl aes-256-cbc -K $encrypted_14f4390ac2b6_key -iv $encrypted_14f4390ac2b6_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
script:
- pwd
- ls -l