language: python
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_14f4390ac2b6_key -iv $encrypted_14f4390ac2b6_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- eval "$(ssh-agent -s)"
- chmod 600 ./secrets/deploy_key
- ssh-add ./secrets/deploy_key
script:
- source ./secrets/travis.env
- python src/deploy.py
after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then curl --verbose -X DELETE "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "X-Auth-Email:$CF_EMAIL" -H "X-Auth-Key:$CF_API_KEY" -H "Content-Type:application/json" --data '{"purge_everything":true}'; fi