services:
  demsausage:
    image: keithmoss/demsausage-django:latest-production
    command: supervisord
    volumes:
      - ./logs/demsausage-django:/app/logs:delegated
    env_file:
      - secrets/sausage-web.env
      - secrets/sausage-db.env
  memcached:
    image: memcached
    command:
      # 5mb to accommodate the larger polling place GeoJSON objects
      - "--max-item-size=5242880"
  rq_dashboard:
    image: keithmoss/demsausage-rq-dashboard:latest-production
    ports:
      - "9181:9181"
    env_file:
      - secrets/rq-dashboard.env
  nginx:
    image: keithmoss/demsausage-nginx:latest-production
    volumes:
      - ./keys/:/app/keys/:delegated
      - ./logs/nginx:/var/log/nginx:delegated
      - ./nginx/docker.prod.demsausage.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - demsausage
      - memcached
      - rq_dashboard
    ports:
      - "443:443"
  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ./logs/demsausage-django:/app/logs/demsausage-django:delegated
      - ./logs/nginx:/app/logs/nginx:delegated
      - ./logs:/app/logs:delegated
    environment:
      - LOGS_DIRECTORIES=/app/logs
      - LOGROTATE_INTERVAL=weekly
      - LOGROTATE_COPIES=520
      - LOGROTATE_SIZE=20M
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_PARAMETERS=f
      - LOGROTATE_LOGFILE=/app/logs/logrotate.log
      - LOGROTATE_DATEFORMAT=-%d-%m-%Y_%H:%M
      - LOGROTATE_OLDDIR=./old
      - TZ=Australia/Perth
