version: "3.7"
services:
  scremsong:
    image: keithmoss/scremsong-django:2.2
    command: supervisord
    volumes:
      - ./logs/scremsong-django:/app/logs:delegated
    env_file:
      - secrets/scremsong-web.env
      - secrets/scremsong-db.env
  # flower:
  #     image: mher/flower
  #     env_file:
  #         - secrets/scremsong-web.env
  #     environment:
  #         - FLOWER_PORT=8888
  #     ports:
  #         - 8888:8888
  nginx:
    image: keithmoss/sausage-nginx:2.2
    volumes:
      - ./keys/:/app/keys/:delegated
      - ./logs/nginx:/var/log/nginx:delegated
      - ./nginx/nginx/docker.prod.scremsong.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - scremsong
    ports:
      - "443:443"
  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ./logs/scremsong-django:/app/logs/scremsong-django:delegated
      - ./logs/nginx:/app/logs/nginx:delegated
    environment:
      - LOGS_DIRECTORIES=/app/logs
      - LOGROTATE_INTERVAL=weekly
      - LOGROTATE_COPIES=520
      - LOGROTATE_SIZE=20M
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_PARAMETERS=f
      - LOGROTATE_LOGFILE=/app/logs/logrotate.log
      - TZ=Australia/Perth
