version: "3.7"
services:
    demsausage:
        image: keithmoss/demsausage-django:latest
        command: supervisord
        volumes:
            - ./logs/demsausage-django:/app/logs:delegated
        env_file:
            - secrets/sausage-web.env
            - secrets/sausage-db.env
    memcached:
        image: memcached
        command:
            # 5mb to accommodate the larger polling place GeoJSON objects
            - '--max-item-size=5242880'
    rq_dashboard:
        build: rq-dashboard/
        entrypoint: /app/docker-entrypoint.sh
        volumes:
            - ./rq-dashboard/:/app:delegated
        ports:
            - "9181:9181"
        env_file:
            - secrets/rq-dashboard.env
    nginx:
        image: keithmoss/sausage-nginx:latest
        volumes:
            - ./keys/:/app/keys/:delegated
            - ./logs/nginx:/var/log/nginx:delegated
            - ./nginx/nginx/docker.prod.demsausage.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - demsausage
            - memcached
            - rq_dashboard
        ports:
            - "443:443"
