version: "2"
services:
  scremsong:
    # build: ./scremsong/django/
    image: keithmoss/scremsong-django:1
    command: runserver
    volumes:
      - ./scremsong/django/:/app:delegated
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=scremsong
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    env_file:
      - scremsong-web-variables.env
  nginx:
    build: nginx/
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx:/app
      - ./nginx/nginx/docker.prod.conf:/etc/nginx/conf.d/nginx.conf
      - ./scremsong/frontend/build/:/scremsong:delegated
    depends_on:
      - scremsong
    ports:
      - "443:443"