version: "2"
services:
  scremsong:
    # build: ./scremsong/django/
    image: keithmoss/scremsong-django:1
    command: runserver
    volumes:
      - ./scremsong/django/:/app:delegated
    ports:
      - "8000:8000"
    env_file:
      - secrets/scremsong-web.env
      - secrets/scremsong-db.env
  pgbackups3:
    image: schickling/postgres-backup-s3
    env_file:
      - secrets/pgbackups3.env
  nginx:
    build: nginx/
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx:/app
      - ./nginx/nginx/docker.prod.conf:/etc/nginx/conf.d/nginx.conf
      - ./scremsong/frontend/build/:/scremsong:delegated
    depends_on:
      - scremsong
    ports:
      - "443:443"