version: "3.7"
services:
    scremsong:
        image: keithmoss/scremsong-django:latest
        command: supervisord
        volumes:
            - ./logs/scremsong-django:/app/logs:delegated
        env_file:
            - secrets/scremsong-web.env
            - secrets/scremsong-db.env
        depends_on:
            - redis
    # flower:
    #     image: mher/flower
    #     env_file:
    #         - secrets/scremsong-web.env
    #     environment:
    #         - FLOWER_PORT=8888
    #     ports:
    #         - 8888:8888
    nginx:
        image: keithmoss/sausage-nginx:latest
        volumes:
            - ./keys/:/app/keys/:delegated
            - ./logs/nginx:/var/log/nginx:delegated
            - ./nginx/nginx/docker.prod.scremsong.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - scremsong
        ports:
            - "443:443"
