version: "3.7"
services:
    scremsong:
        image: keithmoss/scremsong-django:latest
        command: supervisord
        volumes:
            - ./logs/scremsong-django:/app/logs:delegated
        env_file:
            - secrets/scremsong-web.env
            - secrets/scremsong-db.env
    nginx:
        image: keithmoss/sausage-nginx:latest
        volumes:
            - ./keys/:/app/keys/:delegated
            - ./logs/nginx:/var/log/nginx:delegated
            - ./nginx/nginx/docker.prod.scremsong.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - scremsong
            - memcached
        ports:
            - "443:443"
