version: "3.7"
services:
    scremsong:
        image: keithmoss/scremsong-django:latest
        command: supervisord
        volumes:
            - ./logs/django:/app/logs:delegated
        # ports:
        #     - "8000:8000"
        env_file:
            - secrets/scremsong-web.env
            - secrets/scremsong-db.env
    nginx:
        image: keithmoss/sausage-nginx:latest
        volumes:
            - ./keys/:/app/keys/:delegated
            - ./logs/nginx:/var/log/nginx:delegated
            - ./nginx/nginx/docker.dev.conf:/etc/nginx/conf.d/nginx.conf
            # - ./nginx:/app
            # - ./nginx/nginx/docker.prod.conf:/etc/nginx/conf.d/nginx.conf
            # - ./scremsong/frontend/build/:/scremsong/frontend/build:delegated
            # - ./demsausage-v3/public/build/:/demsausage-v3/public/build:delegated
            # - ./demsausage-v3/admin/build/:/demsausage-v3/admin/build:delegated
            # - ./scremsong/django/static:/django/static:delegated
        depends_on:
            - scremsong
        ports:
            - "443:443"
