networks:
  backend-services:
    # Ensure the network is created by this compose file the first time we run it
    external: false
services:
  db:
    container_name: db
    image: ghcr.io/baosystems/postgis:15-3.3
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    networks:
      - backend-services
    env_file:
      - secrets/db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./logs:/etc/postgresql/pg_log

      # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

      # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
      # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/
  # pgbackups3-prod:
  #   image: eeshugerman/postgres-backup-s3:15
  #   restart: always
  #   env_file:
  #     - secrets/pgbackups3-prod.env
  #   depends_on:
  #     - db
  # pgbackups3-staging:
  #   image: eeshugerman/postgres-backup-s3:15
  #   restart: always
  #   env_file:
  #     - secrets/pgbackups3-staging.env
  #   depends_on:
  #     - db
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - backend-services
    volumes:
      - ./redis-data:/data
      - ./redis:/usr/local/etc/redis:ro
    # https://github.com/docker-library/redis/issues/35#issuecomment-360810072
    sysctls:
      net.core.somaxconn: "511"
