networks:
  db:
    # Ensure the network is created by this compose file the first time we run it
    external: false
    name: db
services:
  db:
    container_name: db
    image: ghcr.io/baosystems/postgis:15-3.3
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    networks:
      - db
    env_file:
      - secrets/db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./logs:/etc/postgresql/pg_log

      # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

      # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
      # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/
  # pgbackups3-prod:
  #   image: eeshugerman/postgres-backup-s3:15
  #   restart: always
  #   env_file:
  #     - secrets/pgbackups3-prod.env
  #   depends_on:
  #     - db
  # pgbackups3-staging:
  #   image: eeshugerman/postgres-backup-s3:15
  #   restart: always
  #   env_file:
  #     - secrets/pgbackups3-staging.env
  #   depends_on:
  #     - db