version: "3.7"
services:
    db:
        image: mdillon/postgis:10-alpine
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        ports:
            - "5432:5432"
        env_file:
            - secrets/db.env
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./logs:/etc/postgresql/pg_log

            # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
            - ./postgresql.conf:/etc/postgresql/postgresql.conf

            # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
            # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/
    pgbackups3:
        image: schickling/postgres-backup-s3
        env_file:
            - secrets/pgbackups3.env
        depends_on:
            - db
    rabbitmq:
        image: rabbitmq:3.7.8-alpine
        volumes:
            # Might need to `docker commit` too if we ever change settings? Not sure. (Ref. https://github.com/docker-library/rabbitmq/issues/106#issuecomment-380519695)
            - ./rabbitmq-data:/var/lib/rabbitmq
        ports:
            - "5672:5672"
        env_file:
            - secrets/rabbitmq.env
    redis:
        image: redis:5.0.3-alpine3.8
        ports:
            - "6379:6379"
        # https://github.com/docker-library/redis/issues/35#issuecomment-360810072
        sysctls:
            net.core.somaxconn: "511"
