#cloud-config
write_files:
    - path: /var/tmp/secrets/droplet-deploy.env
      content: |
          {DROPLET_DEPLOY_ENV}
    - path: /var/tmp/secrets/scremsong-web.env
      content: |
          {SCREMSONG_WEB_ENV}
    - path: /var/tmp/secrets/scremsong-db.env
      content: |
          {SCREMSONG_DB_ENV}
    - path: /var/tmp/secrets/pgbackups3.env
      content: |
          {PGBACKUPS3_ENV}
runcmd:
    # Now contained in our DigitalOcean snapshot
    # - sed -i '/^PermitRootLogin/s/yes/without-password/' /etc/ssh/sshd_config
    # # Install dependencies
    # - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    # - echo 'deb http://pkg.cloudflare.com/ xenial main' | sudo tee /etc/apt/sources.list.d/cloudflare-main.list
    # - curl -C - https://pkg.cloudflare.com/pubkey.gpg | sudo apt-key add -
    # # - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    # # - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    # - apt-get update
    # - apt-get install --assume-yes nodejs=8.11.3-1nodesource1 cfca
    # - apt-get install --assume-yes yarn=1.7.0
    # Set the environmnet variables for use in this terminal session
    # https://superuser.com/a/1240860
    - for env in $( cat /var/tmp/secrets/droplet-deploy.env ); do export $(echo $env | sed -e 's/"//g'); done
    - mkdir /apps && cd /apps
    # Install and configure the AWS CLI
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install awscli
    # Checkout our source, and grab our production builds, of Scremsong
    - git clone https://github.com/keithamoss/scremsong.git
    - cd scremsong/frontend/
    - aws s3 cp s3://digitalocean-stack/builds/scremsong-frontend.tar build.tar
    - tar xvf build.tar
    - cd /apps
    # Checkout our source, and grab our production builds, of Democracy Sausage
    - git clone https://github.com/keithamoss/demsausage
    - cd demsausage/public/
    - aws s3 cp s3://digitalocean-stack/builds/demsausage-public.tar build.tar
    - tar xvf build.tar
    - cd ../admin/
    - aws s3 cp s3://digitalocean-stack/builds/demsausage-admin.tar build.tar
    - tar xvf build.tar
    - cd /apps
    # Grab our DigitalOcean stack
    - git clone https://github.com/keithamoss/digitalocean-stack.git
    - cd digitalocean-stack
    - mkdir -p logs/nginx/ && mkdir logs/django/
    - ln -s /apps/scremsong /apps/digitalocean-stack/scremsong
    - ln -s /apps/demsausage /apps/digitalocean-stack/demsausage
    # Setup Nginx with SSL certs from CloudFlare
    - cd nginx
    - cfca getcert -hostnames democracysausage.org,*.democracysausage.org,scremsong.democracysausage.org
    # Docker up!
    - cd /apps/digitalocean-stack
    - mkdir secrets
    - mv /var/tmp/secrets/*.env /apps/digitalocean-stack/secrets/
    - docker-compose up
