#cloud-config
write_files:
    - path: /var/tmp/db.env
      content: |
          POSTGRES_PASSWORD=
          POSTGRES_DB=stack
    - path: /var/tmp/pgbackups3.env
      content: |
          SCHEDULE=@daily
          S3_REGION=
          S3_ACCESS_KEY_ID=
          S3_SECRET_ACCESS_KEY=
          S3_BUCKET=
          S3_PREFIX=
          POSTGRES_HOST=
          POSTGRES_DATABASE=
          POSTGRES_USER=
          POSTGRES_PASSWORD=
          # POSTGRES_EXTRA_OPTS='--schema=public --blobs'
runcmd:
    - sed -i '/^PermitRootLogin/s/yes/without-password/' /etc/ssh/sshd_config
    - mkdir /apps && cd /apps
    # Grab our DigitalOcean stack
    - git clone https://github.com/keithamoss/digitalocean-stack.git
    - cd digitalocean-stack/db/
    - mkdir secrets
    - mv /var/tmp/db.env /apps/digitalocean-stack/db/secrets/db.env
    - mv /var/tmp/pgbackups3.env /apps/digitalocean-stack/db/secrets/pgbackups3.env
    - mkdir postgres-data
    - mkdir -p logs
    - chmod 0777 logs
    - docker-compose up
